AWSTemplateFormatVersion: '2010-09-09'
Description: 'JHR Website CloudFront CDN for S3 Images'

Parameters:
  SourceBucketName:
    Type: String
    Default: jhr-website-images
    Description: The S3 bucket containing images

Resources:
  # CloudFront Distribution (bucket already has public access policy)
  ImageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: JHR Website Image CDN
        Enabled: true
        HttpVersion: http2and3
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf  # CORS-S3Origin
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
        Origins:
          - Id: S3Origin
            DomainName: !Sub '${SourceBucketName}.s3.us-east-1.amazonaws.com'
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 80

Outputs:
  CloudFrontDomain:
    Description: CloudFront distribution domain name
    Value: !GetAtt ImageCDN.DomainName
    Export:
      Name: JHRImageCDNDomain

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref ImageCDN
    Export:
      Name: JHRImageCDNId

  ImageUrlExample:
    Description: Example URL for images via CDN
    Value: !Sub 'https://${ImageCDN.DomainName}/media/your-image.jpg'
